export const seedTreatments: {
  id: string;
  nombre: string;
  precio: number;
  duracion: number;
  descripcion?: string;
}[] = [
  { id: "f1", nombre: "Primera limpieza facial", precio: 10, duracion: 60 },
  { id: "f2", nombre: "Limpieza profunda", precio: 550, duracion: 60 },
  { id: "f3", nombre: "Hidratación y nutrición", precio: 650, duracion: 60 },
  { id: "f4", nombre: "Antioxidante", precio: 650, duracion: 60 },
  { id: "f5", nombre: "Despigmentante", precio: 650, duracion: 60 },
  { id: "f6", nombre: "Antienvejecimiento", precio: 650, duracion: 60 },
  {
    id: "f7",
    nombre: "Antienvejecimiento con mascarilla de oro 24k o caviar negro/rojo",
    precio: 700,
    duracion: 75,
  },
  { id: "f8", nombre: "Acné", precio: 650, duracion: 60 },
  { id: "f9", nombre: "Facial para pieles grasas", precio: 650, duracion: 60 },
  { id: "f10", nombre: "Facial para pieles sensibles", precio: 650, duracion: 60 },
  { id: "f11", nombre: "Delineado permanente de ojos", precio: 1900, duracion: 120 },
  { id: "f12", nombre: "Dermapen para labios", precio: 400, duracion: 45 },
  { id: "f13", nombre: "Dermapen para rostro", precio: 700, duracion: 60 },
  { id: "c1", nombre: "Primer masaje", precio: 550, duracion: 60 },
  { id: "c2", nombre: "Masaje reductivo", precio: 650, duracion: 60 },
  { id: "c3", nombre: "Masaje reductivo cuerpo completo (90 minutos)", precio: 1200, duracion: 90 },
  { id: "c4", nombre: "Levantamiento de glúteos", precio: 650, duracion: 60 },
  { id: "c5", nombre: "Masaje de piernas cansadas", precio: 550, duracion: 60 },
  { id: "c6", nombre: "Limpieza de espalda", precio: 550, duracion: 60 },
  { id: "c7", nombre: "Aclaramiento axilas o zonas íntimas", precio: 490, duracion: 45 },
  { id: "c8", nombre: "Masaje relajante", precio: 600, duracion: 60 },
  { id: "c9", nombre: "Masaje descontracturante", precio: 700, duracion: 60 },
  { id: "c10", nombre: "Masaje con piedras calientes", precio: 700, duracion: 75 },
  { id: "c11", nombre: "Masaje de espalda", precio: 350, duracion: 45 },
  { id: "c12", nombre: "Masaje Lomi Lomi o hawaiano", precio: 700, duracion: 75 },
  { id: "c13", nombre: "Masaje holístico", precio: 800, duracion: 90 },
  { id: "c14", nombre: "Masaje Ayurveda", precio: 700, duracion: 75 },
  { id: "c15", nombre: "Masaje sueco", precio: 650, duracion: 60 },
  { id: "c16", nombre: "Masaje ancestral con rebozo", precio: 700, duracion: 75 },
  { id: "c17", nombre: "Masaje con pindas", precio: 700, duracion: 75 },
  { id: "c18", nombre: "Masaje Maya emocional", precio: 600, duracion: 60 },
  { id: "c19", nombre: "Envoltura corporal", precio: 1100, duracion: 90 },
  { id: "c20", nombre: "Reflexología podal", precio: 450, duracion: 45 },
  { id: "c21", nombre: "Masaje en pareja", precio: 1450, duracion: 90 },
  { id: "e1", nombre: "Pies: exfoliación, envoltura y masaje", precio: 450, duracion: 60 },
  { id: "e2", nombre: "SPA de pies", precio: 550, duracion: 60 },
  { id: "e3", nombre: "Manos: exfoliación, envoltura y masaje", precio: 350, duracion: 45 },
  { id: "e4", nombre: "SPA de manos", precio: 450, duracion: 45 },
  { id: "e5", nombre: "SPA Capilar", precio: 350, duracion: 45 },
  { id: "e6", nombre: "SPA Capilar y Facial", precio: 550, duracion: 75 },
  { id: "m1", nombre: "Manicure con gelish", precio: 350, duracion: 60 },
  { id: "m2", nombre: "Pedicure con gelish", precio: 500, duracion: 75 },
  { id: "m3", nombre: "Retiro de Gelish", precio: 60, duracion: 30 },
  { id: "m4", nombre: "Manicure express sin esmalte", precio: 200, duracion: 30 },
  { id: "m5", nombre: "Pedicure sin esmalte", precio: 400, duracion: 60 },
  { id: "m6", nombre: "Gelish Francés", precio: 280, duracion: 45 },
  { id: "m7", nombre: "Manicure y Pedicure", precio: 850, duracion: 120 },
  { id: "m8", nombre: "Retoque de acrigel", precio: 350, duracion: 60 },
  { id: "m9", nombre: "Baño de acrigel", precio: 350, duracion: 60 },
  { id: "m10", nombre: "Calcio", precio: 120, duracion: 30 },
  { id: "m11", nombre: "Calcio con gel", precio: 320, duracion: 45 },
  {
    id: "m12",
    nombre: "Retiro de acrílico",
    precio: 125,
    duracion: 45,
    descripcion: "Precio variable $100-$150",
  },
  { id: "m13", nombre: "Rubber", precio: 200, duracion: 45 },
  {
    id: "m14",
    nombre: "Pedrería",
    precio: 8,
    duracion: 15,
    descripcion: "Precio por pieza $5-$10",
  },
  { id: "d1", nombre: "Zonas pequeñas", precio: 300, duracion: 30 },
  { id: "d2", nombre: "Zonas medianas", precio: 500, duracion: 45 },
  { id: "d3", nombre: "Zonas grandes", precio: 700, duracion: 60 },
  { id: "d4", nombre: "Cuerpo completo", precio: 1100, duracion: 90 },
];
